import Config

# Configure your database
config :ysc, Ysc.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "ysc_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :ysc, YscWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [
    ip: {0, 0, 0, 0},
    port: String.to_integer(System.get_env("PORT") || "4000")
  ],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base:
    "HVfMgcL35fAJz7aiwv581CSXDiPTWHDuSQcqIL4gkkPomNfXjUo4MENFgQ1U4sZF",
  watchers: [
    esbuild:
      {Esbuild, :install_and_run, [:default, ~w(--sourcemap=inline --watch)]},
    esbuild_admin:
      {Esbuild, :install_and_run, [:admin, ~w(--sourcemap=inline --watch)]},
    esbuild_html5_qrcode:
      {Esbuild, :install_and_run, [:html5_qrcode, ~w(--watch)]},
    tailwind: {Tailwind, :install_and_run, [:default, ~w(--watch)]},
    tailwind_admin: {Tailwind, :install_and_run, [:admin, ~w(--watch)]}
  ],
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"assets/js/.*(js)$",
      ~r"assets/css/.*(css)$",
      ~r"assets/vendor/.*(js)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/ysc_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :ysc, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Chrome/ChromicPDF: give headless Chrome longer to cold-start on macOS.
# If you don't need TV-poster generation locally, set CHROMIC_PDF_ENABLED=false in .env instead.
config :ysc, ChromicPDF, session_pool: [init_timeout: 30_000]

config :ex_aws,
  access_key_id: "minioadmin",
  secret_access_key: "minioadmin",
  debug_requests: true,
  s3: [
    scheme: "http://",
    host: "localhost",
    port: 9000
  ]

config :ysc,
  s3_base_url: "http://localhost:9000",
  # Overrides for testing on a physical device / Android emulator, where
  # "localhost:9000" resolves to the device itself, not this machine's MinIO —
  # set these to this machine's LAN IP (e.g. "http://192.168.1.50:9000") so
  # avatar/media images actually load. Unset falls back to localhost, unchanged.
  s3_media_public_url: System.get_env("S3_MEDIA_PUBLIC_BASE_URL"),
  s3_avatars_public_url: System.get_env("S3_AVATARS_PUBLIC_BASE_URL"),
  aws_access_key_id: "minioadmin",
  aws_secret_access_key: "minioadmin",
  expense_reports_s3_bucket: "expense-reports",
  app_resources_s3_bucket: "app-resources",
  avatars_s3_bucket: "avatars",
  membership_plans: [
    %{
      id: :single,
      name: "Single",
      interval: "year",
      amount: 45,
      currency: "usd",
      trial_period_days: 0,
      stripe_price_id: "price_1SIE3vRMG501eq4FsxHj8mZQ",
      statement_descriptor: "Single Membership",
      description: "Membership just for yourself",
      metadata: %{
        "plan_type" => "membership",
        "interval" => "year"
      }
    },
    %{
      id: :family,
      name: "Family",
      interval: "year",
      amount: 65,
      currency: "usd",
      trial_period_days: 0,
      stripe_price_id: "price_1SIE4lRMG501eq4FscHCTXOl",
      statement_descriptor: "Family Membership",
      description: "For you, your Spouse and your children under 18",
      metadata: %{
        "plan_type" => "membership",
        "interval" => "year"
      }
    }
  ]

# Include HEEx debug annotations as HTML comments in rendered markup
config :phoenix_live_view, :debug_heex_annotations, true

# Kiosk API key for property kiosk app authentication (can be overridden via env var)
config :ysc, :kiosk_api_key, System.get_env("KIOSK_API_KEY") || "dev-kiosk-key"

# Stripe Terminal location for the admin/volunteer mobile app's tap-to-pay
# connection tokens (can be overridden via env var once a real test-mode
# Location exists in the Stripe Dashboard).
config :ysc,
       :stripe_terminal_location_id,
       System.get_env("STRIPE_TERMINAL_LOCATION_ID")

# OAuth Configuration for development
# Set these via environment variables or use test values
config :ueberauth, Ueberauth.Strategy.Google.OAuth,
  client_id: System.get_env("GOOGLE_CLIENT_ID") || "dev_google_client_id",
  client_secret:
    System.get_env("GOOGLE_CLIENT_SECRET") || "dev_google_client_secret"

config :ueberauth, Ueberauth.Strategy.Facebook.OAuth,
  client_id: System.get_env("FACEBOOK_CLIENT_ID") || "dev_facebook_client_id",
  client_secret:
    System.get_env("FACEBOOK_CLIENT_SECRET") || "dev_facebook_client_secret"

config :ysc, :google_photos,
  client_id: System.get_env("GOOGLE_PHOTOS_CLIENT_ID"),
  client_secret: System.get_env("GOOGLE_PHOTOS_CLIENT_SECRET"),
  redirect_uri: System.get_env("GOOGLE_PHOTOS_REDIRECT_URI"),
  dev_stub: System.get_env("GOOGLE_PHOTOS_DEV_STUB", "true") in ~w(true 1 yes)

# Standalone Query Console (admin sidebar → opens in a new tab).
config :ysc,
       :query_console_url,
       System.get_env("QUERY_CONSOLE_URL") || "http://localhost:4001"

# First-party OAuth clients (authorization-code + PKCE). Keyed by client_id.
# Add another map entry to register a new app; roles/states gate who may authorize.
config :ysc, :oauth_clients, %{
  (System.get_env("QUERY_CONSOLE_SSO_CLIENT_ID") || "query_console_dev") => %{
    client_secret:
      System.get_env("QUERY_CONSOLE_SSO_CLIENT_SECRET") ||
        "dev_secret_change_me",
    redirect_uris:
      (System.get_env("QUERY_CONSOLE_SSO_REDIRECT_URIS") ||
         "http://localhost:4001/auth/ysc/callback")
      |> String.split(",", trim: true)
      |> Enum.map(&String.trim/1)
      |> Enum.reject(&(&1 == "")),
    post_logout_redirect_uris:
      (System.get_env("QUERY_CONSOLE_SSO_POST_LOGOUT_REDIRECT_URIS") ||
         "http://localhost:4001/auth/signed-out")
      |> String.split(",", trim: true)
      |> Enum.map(&String.trim/1)
      |> Enum.reject(&(&1 == "")),
    roles: [:admin],
    states: [:active]
  }
}

# Wax (WebAuthn) configuration for development
#
# RP ID: "localhost" (development only - each environment has separate passkeys)
# Origin: Must match the actual origin where the app runs
#
# Note: For production subdomain sharing, set WEBAUTHN_RP_ID environment variable
# to the base domain (e.g., "ysc.org") to allow passkeys to work across subdomains
config :wax_,
  rp_id: "localhost",
  origin: "http://localhost:4000",
  attestation: "none"
