defmodule QueryConsoleWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :query_console

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @base_session_options [
    store: :cookie,
    key: "_query_console_key",
    signing_salt: "CwUCRRhf",
    same_site: "Lax",
    http_only: true
  ]

  # In production (no code reloader), require HTTPS for the session cookie.
  # In development we omit :secure so local HTTP works.
  @session_options (if code_reloading? do
                      @base_session_options
                    else
                      Keyword.put(@base_session_options, :secure, true)
                    end)

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :query_console,
    gzip: not code_reloading?,
    only: QueryConsoleWeb.static_paths()

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :query_console
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug QueryConsoleWeb.Router
end
